spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentACarDB?createDatabaseIfNotExist=true
    username: root
    password: 9696
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dll-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
loggin:
  level:
    org:
      hibernate:
        type:
          trace